name: Default Meshery Istio Workflow
on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
    paths-ignore:
      - "docs/**"
      - ".github/**"
  pull_request:
    branches:
      - master
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest
          args: --timeout=5m
  tests:
    #  needs: [lint, error_check, static_check, vet, sec_check]
    name: Tests
    runs-on: ubuntu-22.04
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Create cluster using KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - run: |
          export CURRENTCONTEXT="$(kubectl config current-context)"
          echo "current-context:" ${CURRENTCONTEXT}   
          export KUBECONFIG="${HOME}/.kube/config"
          echo "environment-kubeconfig:" ${KUBECONFIG}
          GOPROXY=https://proxy.golang.org,direct GOSUMDB=off GO111MODULE=on go test -v ./...
